import type { ComponentType, CSSProperties } from "react";
import {
  SiPython,
  SiCplusplus,
  SiR,
  SiGnubash,
  SiTensorflow,
  SiPytorch,
  SiScikitlearn,
  SiKeras,
  SiHuggingface,
  SiLangchain,
  SiNumpy,
  SiPandas,
  SiGooglecloud,
  SiApachespark,
  SiApachekafka,
  SiApacheairflow,
  SiApachehadoop,
  SiDocker,
  SiPostgresql,
  SiMysql,
  SiSnowflake,
  SiDatabricks,
  SiPlotly,
  SiNumba,
  SiGit,
  SiGithub,
  SiGitlab,
  SiOpenai,
  SiJupyter,
  SiOptuna,
  SiStreamlit,
  SiDbt,
  SiRust,
  SiClaude,
} from "react-icons/si";
import { BloombergIcon, OandaIcon } from "../components/ui/customIcons";

type IconComponent = ComponentType<{ className?: string; style?: CSSProperties }>;

/** Normalize a tech label to a lookup key. */
export function techKey(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]/g, "");
}

/** Simple Icons + custom brand glyphs. Anything not here renders as a text chip. */
export const techIcons: Record<string, IconComponent> = {
  python: SiPython,
  c: SiCplusplus,
  r: SiR,
  bash: SiGnubash,
  tensorflow: SiTensorflow,
  pytorch: SiPytorch,
  scikitlearn: SiScikitlearn,
  keras: SiKeras,
  huggingface: SiHuggingface,
  huggingfacetransformers: SiHuggingface,
  langchain: SiLangchain,
  numpy: SiNumpy,
  pandas: SiPandas,
  googlecloud: SiGooglecloud,
  bigquery: SiGooglecloud,
  apachespark: SiApachespark,
  spark: SiApachespark,
  apachekafka: SiApachekafka,
  kafka: SiApachekafka,
  apacheairflow: SiApacheairflow,
  airflow: SiApacheairflow,
  hadoop: SiApachehadoop,
  docker: SiDocker,
  postgresql: SiPostgresql,
  mysql: SiMysql,
  snowflake: SiSnowflake,
  databricks: SiDatabricks,
  plotly: SiPlotly,
  numbajit: SiNumba,
  numba: SiNumba,
  git: SiGit,
  github: SiGithub,
  gitlab: SiGitlab,
  openai: SiOpenai,
  gpt4: SiOpenai,
  gpt2: SiOpenai,
  jupyter: SiJupyter,
  optuna: SiOptuna,
  streamlit: SiStreamlit,
  dbt: SiDbt,
  rust: SiRust,
  claudecode: SiClaude,
  claude: SiClaude,
  bloomberg: BloombergIcon,
  oanda: OandaIcon,
};

/** Brand colors chosen to read well on a near-black background. */
export const techColors: Record<string, string> = {
  python: "#4B8BBE",
  c: "#649AD2",
  r: "#276DC3",
  bash: "#7CC04B",
  tensorflow: "#FF6F00",
  pytorch: "#EE4C2C",
  scikitlearn: "#F7931E",
  keras: "#FF4136",
  huggingface: "#FFD21E",
  langchain: "#3FB984",
  numpy: "#4DABCF",
  pandas: "#E70488",
  googlecloud: "#4285F4",
  bigquery: "#669DF6",
  apachespark: "#E25A1C",
  spark: "#E25A1C",
  apachekafka: "#D6D6D6",
  kafka: "#D6D6D6",
  apacheairflow: "#36B7F0",
  airflow: "#36B7F0",
  hadoop: "#FFCA28",
  docker: "#2496ED",
  postgresql: "#5A8DD6",
  mysql: "#4479A1",
  snowflake: "#29B5E8",
  databricks: "#FF3621",
  plotly: "#7C84F0",
  numba: "#00A3E0",
  numbajit: "#00A3E0",
  git: "#F05032",
  github: "#EDEDED",
  gitlab: "#FC6D26",
  openai: "#74AA9C",
  gpt4: "#74AA9C",
  gpt2: "#74AA9C",
  jupyter: "#F37626",
  optuna: "#2D6CDF",
  streamlit: "#FF4B4B",
  dbt: "#FF694B",
  rust: "#DEA584",
  claudecode: "#D97757",
  claude: "#D97757",
  vertexai: "#4285F4",
  openrouter: "#7B83EB",
  faiss: "#4267B2",
  chromadb: "#FFB000",
  bloomberg: "#FF9E1B",
  oanda: "#00A9CE",
  // text-fallback tiles that still deserve their brand hue
  aws: "#FF9900",
  azure: "#3FA9F5",
  tableau: "#4E79A7",
  powerbi: "#F2C811",
};

export function getTechIcon(name: string): IconComponent | undefined {
  return techIcons[techKey(name)];
}

export function getTechColor(name: string): string | undefined {
  return techColors[techKey(name)];
}
